# Generated by Django 3.0.7 on 2020-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200630_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='time',
            field=models.BigIntegerField(default=2),
        ),
    ]
